### ISSUE TITLE
Add links

### ISSUE THREAD

**Issue by mmathys** [cnnmon/ezcv#4]
It would be useful to add clickable links for mails and websites. Links could be added in md style:

```
[firstlast@gmail.com](mailto:firstlast@gmail.com)
```

Very useful app, will definitely use it :)

**Comment by mmathys** [comment]
Nevermind, this feature is already implemented.

**Comment by mmathys** [comment]
For example, it would be cool if this link could be rendered as a link in the PDF:

```
github.com/mmathys
```

**Comment by cnnmon** [comment]
Yup, it's not clickable on the live render but it is clickable in the PDF version. Thanks for pointing it out though!
